name: Node

on:
  - push

jobs:
  deploy-page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16

      - run: npm ci
        working-directory: hardhat/app/
      - run: npm run lint
        working-directory: hardhat/app/
      - run: npm run build
        working-directory: hardhat/app/

      - uses: JamesIves/github-pages-deploy-action@4.0.0
        working-directory: hardhat/app/
        with:
          branch: gh-pages
          folder: ./dist
          single-commit: true
          silent: false
